name: Build and Push Docker Image

on:
    push:
        branches:
            - main

permissions:
  contents: read
  packages: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract GitHub SHA
              id: github_sha
              run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

            - name: Get latest tag
              id: get-latest-tag
              uses: actions-ecosystem/action-get-latest-tag@v1

            - name: Bump version and get new tag
              id: new_version
              uses: actions-ecosystem/action-bump-semver@v1
              with:
                current_version: ${{ steps.get-latest-tag.outputs.tag }}
                level: minor

            - name: Log in to Github Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}


            - name: Build and tag Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/f5xc-frpc:latest, ghcr.io/${{ github.repository_owner }}/f5xc-frpc:${{ steps.new_version.outputs.new_version }}
              
            - name: Create new tag
              run: git tag -a ${{ steps.new_version.outputs.new_version }}

            - name: Push new tag
              run: git push origin ${{ steps.new_version.outputs.new_version }}